version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pulse-local
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: pulse_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
